### ISSUE TITLE
Scroll creation removed

### ISSUE THREAD

**Issue by BardezAnAvatar** [Gibberlings3/Skills-and-Abilities#47]
Looks like scroll creation was removed; is there a plan to reimplement in this mod, or is it permanently removed? Is there a sharable reason for removing it?

**Comment by morpheus562** [comment]
Because Endarire meddled to make it work for his super niche setup he never plays. Grammar, who built out that component, tried to accommodate but it broke somewhere. Grammar is stepping away from coding now and I do not want to dig into it to determine 1) how it was coded to work and 2) figure out what exactly caused it to break. Endarire is why we can't have nice things.

**Comment by BardezAnAvatar** [comment]
Thanks for the response. Sounds like it's dead-dead and not merely off while working out kinks.
